CREATE TABLE NGUOI_O_CUNG (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hop_dong_id BIGINT NOT NULL REFERENCES HOP_DONG(id) ON DELETE CASCADE,
    nguoi_thue_id BIGINT NOT NULL REFERENCES NGUOI_THUE(id),
    quan_he VARCHAR(100) NOT NULL,
    tu_ngay DATE NOT NULL,
    den_ngay DATE,
    CONSTRAINT ck_nguoi_o_cung_khoang_ngay CHECK (den_ngay IS NULL OR den_ngay >= tu_ngay)
);

CREATE INDEX ix_nguoi_o_cung_hop_dong_ngay
    ON NGUOI_O_CUNG(hop_dong_id, tu_ngay, den_ngay);

CREATE INDEX ix_nguoi_o_cung_nguoi_thue
    ON NGUOI_O_CUNG(nguoi_thue_id);
