CREATE TABLE XAC_NHAN_CANH_BAO_CHI_SO (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chi_so_dich_vu_id BIGINT NOT NULL REFERENCES CHI_SO_DICH_VU(id) ON DELETE CASCADE,
    nguoi_xac_nhan_id BIGINT NOT NULL REFERENCES NGUOI_DUNG(id),
    muc_tieu_thu_ky_nay NUMERIC(15,2) NOT NULL CHECK (muc_tieu_thu_ky_nay >= 0),
    trung_binh_ba_ky_truoc NUMERIC(15,2) NOT NULL CHECK (trung_binh_ba_ky_truoc >= 0),
    gap_trung_binh NUMERIC(15,2) NOT NULL CHECK (gap_trung_binh >= 0),
    thoi_diem_xac_nhan TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
