CREATE TABLE NHAN_KHAU_KY (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ky_id BIGINT NOT NULL REFERENCES KY_THANH_TOAN(id),
    phong_id BIGINT NOT NULL REFERENCES PHONG(id),
    so_nguoi INTEGER NULL CHECK (so_nguoi >= 0),
    thoi_diem_chot TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_nhan_khau_ky_ky_phong UNIQUE (ky_id, phong_id)
);

CREATE INDEX ix_nhan_khau_ky_phong_ky
    ON NHAN_KHAU_KY (phong_id, ky_id);
