CREATE TABLE KHOAN_PHAT_SINH (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hop_dong_id BIGINT NOT NULL REFERENCES HOP_DONG(id),
    nguon_loai VARCHAR(30) NOT NULL,
    nguon_id BIGINT NOT NULL,
    ten_khoan VARCHAR(255) NOT NULL,
    so_tien NUMERIC(15,2) NOT NULL,
    loai VARCHAR(30) NOT NULL CHECK (
        loai IN ('PHAT_SINH', 'GIAM_TRU')
    ),
    trang_thai VARCHAR(30) NOT NULL CHECK (
        trang_thai IN ('CHO_TINH', 'DA_TINH')
    ),
    hoa_don_id BIGINT NULL REFERENCES HOA_DON(id)
);

CREATE INDEX ix_khoan_phat_sinh_hop_dong_trang_thai
    ON KHOAN_PHAT_SINH (hop_dong_id, trang_thai, id);

CREATE INDEX ix_khoan_phat_sinh_hoa_don
    ON KHOAN_PHAT_SINH (hoa_don_id);
