ALTER TABLE HOA_DON
    ADD COLUMN so_nguoi_o INTEGER NULL CHECK (so_nguoi_o IS NULL OR so_nguoi_o >= 0),
    ADD COLUMN so_ho_quy_doi INTEGER NULL CHECK (so_ho_quy_doi IS NULL OR so_ho_quy_doi >= 0),
    ADD COLUMN giai_thich_so_ho TEXT NULL;

ALTER TABLE CHI_TIET_HOA_DON
    ADD COLUMN dien_giai TEXT NULL;

CREATE TABLE CHI_TIET_HOA_DON_BAC_THANG (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chi_tiet_hoa_don_id BIGINT NOT NULL REFERENCES CHI_TIET_HOA_DON(id) ON DELETE CASCADE,
    bac INTEGER NOT NULL CHECK (bac > 0),
    tu_so_luong NUMERIC(15,2) NOT NULL,
    den_so_luong NUMERIC(15,2) NULL,
    dinh_muc_quy_doi NUMERIC(15,2) NULL,
    so_luong NUMERIC(15,2) NOT NULL,
    don_gia NUMERIC(15,2) NOT NULL,
    thanh_tien NUMERIC(15,2) NOT NULL
);

CREATE INDEX ix_chi_tiet_hoa_don_bac_thang_chi_tiet
    ON CHI_TIET_HOA_DON_BAC_THANG (chi_tiet_hoa_don_id, bac);
