ALTER TABLE THONG_BAO
    DROP CONSTRAINT IF EXISTS thong_bao_doi_tuong_loai_check;

ALTER TABLE THONG_BAO
    ADD CONSTRAINT ck_thong_bao_doi_tuong_loai
        CHECK (doi_tuong_loai IN ('YEU_CAU_SUA_CHUA', 'HOA_DON', 'THONG_BAO_CHUNG'));

ALTER TABLE ANH_DINH_KEM
    DROP CONSTRAINT IF EXISTS anh_dinh_kem_doi_tuong_loai_check;

ALTER TABLE ANH_DINH_KEM
    ADD CONSTRAINT ck_anh_dinh_kem_doi_tuong_loai
        CHECK (doi_tuong_loai IN ('NGUOI_THUE', 'CHI_SO_DICH_VU', 'YEU_CAU_SUA_CHUA', 'THONG_BAO_CHUNG'));

CREATE TABLE THONG_BAO_CHUNG (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_tham_chieu UUID NOT NULL UNIQUE,
    nguoi_gui_id BIGINT NOT NULL REFERENCES NGUOI_DUNG(id),
    toa_nha_id BIGINT NOT NULL REFERENCES TOA_NHA(id),
    pham_vi VARCHAR(20) NOT NULL CHECK (pham_vi IN ('TOA_NHA', 'TANG', 'PHONG')),
    tang INTEGER NULL CHECK (tang IS NULL OR tang > 0),
    phong_ids TEXT NOT NULL DEFAULT '',
    tieu_de VARCHAR(255) NOT NULL,
    noi_dung TEXT NOT NULL,
    het_han_luc TIMESTAMPTZ NOT NULL,
    khoa_chong_lap VARCHAR(255) NOT NULL,
    dau_vao_hash CHAR(64) NOT NULL,
    so_nguoi_nhan INTEGER NOT NULL CHECK (so_nguoi_nhan >= 0),
    so_phong_nhan INTEGER NOT NULL CHECK (so_phong_nhan >= 0),
    so_phong_khong_co_tai_khoan INTEGER NOT NULL CHECK (so_phong_khong_co_tai_khoan >= 0),
    tao_luc TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_thong_bao_chung_pham_vi CHECK (
        (pham_vi = 'TOA_NHA' AND tang IS NULL AND phong_ids = '')
        OR (pham_vi = 'TANG' AND tang IS NOT NULL AND phong_ids = '')
        OR (pham_vi = 'PHONG' AND tang IS NULL AND phong_ids <> '')
    ),
    CONSTRAINT uq_thong_bao_chung_khoa UNIQUE (nguoi_gui_id, khoa_chong_lap)
);

CREATE INDEX ix_thong_bao_chung_nguoi_gui ON THONG_BAO_CHUNG (nguoi_gui_id, tao_luc DESC);
CREATE INDEX ix_thong_bao_chung_het_han ON THONG_BAO_CHUNG (het_han_luc);
