CREATE TABLE NHAC_TIEN_MOC (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hoa_don_id BIGINT NOT NULL REFERENCES HOA_DON(id),
    nguoi_nhan_id BIGINT NOT NULL REFERENCES NGUOI_DUNG(id),
    moc_ngay INTEGER NOT NULL CHECK (moc_ngay IN (-3, 1, 5)),
    trang_thai VARCHAR(20) NOT NULL CHECK (trang_thai IN ('DA_GUI')),
    gui_luc TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_nhac_tien_moc UNIQUE (hoa_don_id, nguoi_nhan_id, moc_ngay)
);

CREATE INDEX ix_nhac_tien_moc_hoa_don_nguoi_nhan
    ON NHAC_TIEN_MOC (hoa_don_id, nguoi_nhan_id, moc_ngay);

CREATE TABLE NHAT_KY_NHAC_TIEN (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hoa_don_id BIGINT NOT NULL REFERENCES HOA_DON(id),
    nguoi_nhan_id BIGINT NULL REFERENCES NGUOI_DUNG(id),
    moc_ngay INTEGER NULL CHECK (moc_ngay IS NULL OR moc_ngay IN (-3, 1, 5)),
    ngay_nghiep_vu DATE NOT NULL,
    trang_thai VARCHAR(20) NOT NULL CHECK (trang_thai IN ('THANH_CONG', 'THAT_BAI')),
    loi TEXT NULL,
    thoi_diem TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX ix_nhat_ky_nhac_tien_hoa_don_thoi_diem
    ON NHAT_KY_NHAC_TIEN (hoa_don_id, thoi_diem DESC);
